common.o: common.c common.h
ser_path.o: ser_path.c common.h ser_path_def.h ser_path.h
ser_path_djk.o: ser_path_djk.c common.h ser_path_def.h ser_path.h
ser_path_tc.o: ser_path_tc.c common.h ser_path_def.h ser_path.h
ser_path_test.o: ser_path_test.c common.h ser_path_def.h ser_path.h
ser_valider_tc.o: ser_valider_tc.c common.h ser_path.h
